### PR TITLE
draw root only for empty sparse tree

### PR DESCRIPTION
**Pull request by nullset-mit**
Currently crashes instead.

### CODE REVIEW

**Comment by nandeeka** [comment]
Hi @gfm-mit , Thanks for opening this PR. Would it be possible for you to provide an example of crashing code. The example of an "empty sparse tree" that I  can think of:
```
t = Tensor(rank_ids=["K", "M"])
displayTensor(t)
```
seems to work fine for me.
Thanks!

**Comment by nullset-mit** [comment]
Interesting!  I wonder if it's because in class we were using prelude-v1.py?

Screenshot 2023-05-19 at 11 20 08 PM

What's your preferred environment for testing this kind of thing?

**Comment by nandeeka** [comment]
If you think it is the prelude, you can try sending your version. Additionally, make sure you are testing this with latest version of the repository. I think the one that comes with the docker container is months, if not years, out of date.

**Comment by nullset-mit** [comment]
oh man, sorry, I had no idea I was using an out of date version.  rookie mistake!

**Comment by jsemer** [comment]
Abraham - I don't think you were using an out-of-date version. The docker container used in class had an up-to-date version of the fibertree code. And now when I try to run a variety of notebooks they need this fix. Nandeeka - there must be some environmental difference that allows it to work for you that we should look into. In addition, there are other display problem in the fibertree.ipynb notebook that need to be investigated...

**Comment by jsemer** [comment]
Manually merged to separate the two commits.

**Pull request closed without merging**
